# Generated by Django 5.0.7 on 2024-07-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='my freaking blog', max_length=255),
        ),
    ]
