# Generated by Django 5.0.7 on 2024-08-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
