# Generated by Django 5.0.7 on 2024-10-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_remove_category_image_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
